### ISSUE TITLE
Make a better support for PC and VR players to play together

### ISSUE THREAD

**Issue by iDarknessSam** [FoxComment/KoboldKare-VR-Mod#2]
Hello I tried to play this game here however I don't have a VR but some of my friends have, I would like to play with them using this version of Kobold Kare
however I found some problems here...one of them was because of the camera, I can't move my mouse up and down, I can only move left and right, I would like if someone fix this...
also for some reason the multiplayer mode doesn't work, I tried to click on the multiplayer tab but it just keep loading infinity until I need to force exit.

**Comment by FoxComment** [comment]
I cannot use/connect to official KK servers.
